name: "Clear website cache"
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Call website clear cache endpoint
        run: |
          curl -X POST https://www.imaginando.pt/cache/clear
