name: Publish

on:
  push:
    branches: [master]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-image-dimensions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --production

      - name: Run custom npm command
        run: npm run build:image-dimensions image-dimensions.json

      - name: Commit changes
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add image-dimensions.json
          git commit -m "Build image-dimensions.json"
          git push

  build-pages:
    runs-on: ubuntu-latest
    needs: build-image-dimensions
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  clear-website-cache:
    runs-on: ubuntu-latest
    needs: deploy-pages
    steps:
      - name: Call website clear cache endpoint
        run: |
          curl -X POST https://www.imaginando.pt/cache/clear
